Add development encoded value to identify built-up areas
graphhopper/graphhopper pull request #2637
Opened 2022-07-29 10:38 UTC by easbar

Fixes #2395.

This PR adds a new encoded value `development=country/residential/city` distinguishes country roads from residential areas and residential areas from city centers. The calculation is rather simple, but seems quite effective: For every edge we run a breadth-first search to determine the road density in the vicinity of the edge. In a first run we use a small radius (300m currently) to find all residential areas. In a second run we use a larger radius (2000m currently) to find dense residential areas that we then classify as 'city' (centers). The first run is quite fast due to the small radius, why the second one takes significantly longer. The calculation is run in parallel so it strongly benefits from hardware with multiple cores. 
A possible improvement might be also considering OSM buildings (or OSM landuse tags, satellite imagery and what not). But one advantage of the current approach is that it works with the graph we are already creating anyway, so I thought it would be a good idea to figure out how far this can take us first.

To enable the feature set `graph.development.threads` to some value larger or equal to 1 (higher values make the calculation faster).

I also added visualization of the development encoded value to the maps app (see the 'Show Development' check box in the layers menu) (blue=country, yellow=residential, red=city).

One use-case is finding village boundaries in rural areas (related to #2392, @westnordost). For example when a secondary road is crossing a village and there are no max_speed tags, the `development` encoded value still allows to slow down the speed. For example this [route](http://localhost:8989/maps/?point=49.885123%2C9.602051&point=50.010387%2C9.856453&locale=en-US&elevation=true&profile=car&details=development&details=road_class&details=max_speed&use_miles=false&selected_detail=development&layer=OpenStreetMap)

![image](https://user-images.githubusercontent.com/17603532/181737993-4a603369-573c-403f-9fc6-f92a6c341131.png)

crosses several villages (seen as red clusters on the map and dark blue sections in the elevation diagram).

But we cannot tell this from the road class (highway tag) only. For example for the first part the route just follows a secondary highway and the road class does not change within the villages.

![image](https://user-images.githubusercontent.com/17603532/181738231-41769d37-2c21-4609-8e79-4e91c3c48af0.png)

The max speeds are not mapped sufficiently either:

![image](https://user-images.githubusercontent.com/17603532/181738338-14600f85-c988-4c8f-a05f-d709a555f967.png)

Another use case might be finding city centers where high traffic must be expected. Here is a screenshot of Munich:

![image](https://user-images.githubusercontent.com/17603532/181738874-04c1c9c0-2ff7-4701-80eb-2501eac62a5c.png)

I spent some time tuning the parameters to (visually) find a good ratio between false positives (e.g. roads outside of residential areas that are classified as residential) and false negatives (e.g. residential/city area roads that are classified as country/residential), but there still might be room to improve this. Still, I think the feature is already useful in its current state. Currently the biggest downside is the additional import time that is required especially for the city classification. Running the residential classification only is much faster (use `graph.development.city_radius: 0` to disable the city classification).

2022-07-29 11:20 UTC, westnordost commented
Whoa, cool! But, how do you determine if a road is in a built-up area or in a rural area?

@kevinkreiser has been working on something maybe similar, see https://github.com/valhalla/valhalla/issues/3334#issuecomment-1198408988 . If this is not directly useful (to each other), at least the mechanism to evaluate the mapillary data for common speed limits could be used to aggregate into the residential/urban distinction.

2022-07-29 12:54 UTC, easbar commented
> But, how do you determine if a road is in a built-up area or in a rural area?

This approach is purely based on the road density. So basically we count how many other road meters are in the neighborhood of the given road, if there are lots of other roads around we conclude it must be a residential area. See the beginning ob my above post for a few more details.

2022-07-29 14:54 UTC, kevinkreiser commented
@easbar @westnordost that is exactly the same measurement i used over in valhalla and openstreetmapspeeds

2022-07-29 16:52 UTC, westnordost commented
Ah!

In the United States in particular, "residential districts" and "business districts" ( ~ urban) are usually defined like this and similar:

> "Urban residence district" shall mean the territory contiguous to a highway not comprising a business district when the frontage on such highway for a distance of 300 feet or more is mainly occupied by dwellings or by dwellings and buildings in use for business.

\- [2021 New Hampshire Revised Statutes, Title XXI - Motor Vehicles, Title 259 - Words and Phrases Defined, Section 259:118 - Urban Residence District.](https://law.justia.com/codes/new-hampshire/2021/title-xxi/title-259/section-259-118/)

So maybe if you added the number/area of buildings into the equation, you could both improve the accuracy of this data. Because after all, roads where there are (many) buildings near, are more likely to be urban in respect to speed limit restrictions. 

E.g. from the current data, [linear settlements ](https://en.wikipedia.org/wiki/Linear_settlement) (de: Straßendorf) would probably not be detected correctly.

2022-08-31 07:09 UTC, otbutz requested changes

2022-08-31 07:09 UTC, otbutz commented on core/src/main/java/com/graphhopper/util/GHUtility.java
> +    public static void runConcurrently(Stream<Callable<String>> callables, int threads) {
Is there a reason why we use `Callable<String>` instead of `Runnable` ? We seem to ignore the result anyway.

2022-08-31 07:09 UTC, otbutz commented on core/src/main/java/com/graphhopper/util/GHUtility.java
>              executorService.shutdownNow();
Can we move all shutdown logic into a `finally` block?

2022-08-31 08:29 UTC, easbar commented on core/src/main/java/com/graphhopper/routing/util/DevelopmentCalculator.java
> +        logger.info("Finished calculating residential areas, took: " + sw.stop().getSeconds() + "s");
No. This has nothing to do with the logging. The residential classification uses a smaller radius (faster) and runs for all edges, while the city classification only counts edges that were already classified as residential (and potentially promotes them to 'city') but with a larger radius (much slower). I found that this works quite well, but of course there might be other ways to do this.

2022-08-31 08:59 UTC, merged

2022-08-31 09:00 UTC, otbutz commented on core/src/main/java/com/graphhopper/routing/util/DevelopmentCalculator.java
> +        logger.info("Finished calculating residential areas, took: " + sw.stop().getSeconds() + "s");
Can't we reuse the same calculator with a different radius and work with early-out conditions?

Basically:

```java
if (roadClass != RoadClass.RESIDENTIAL && roadClass != RoadClass.LIVING_STREET) {
    double roadDensity = calculator.calcRoadDensity(edge, residentialAreaRadius, calcRoadFactor);
    if (roadDensity * residentialAreaSensitivity < 1.0) {
        return RURAL;
    }
}

if (!calcCity) {
  return RESIDENTIAL;
}

double roadDensity = calculator.calcRoadDensity(edge, cityAreaRadius, calcRoadFactor);
if (roadDensity * cityAreaSensitivity < 1.0) {
    return RESIDENTIAL;
}

return CITY;
```

2022-08-31 09:08 UTC, easbar commented on core/src/main/java/com/graphhopper/routing/util/DevelopmentCalculator.java
> +        logger.info("Finished calculating residential areas, took: " + sw.stop().getSeconds() + "s");
But why would this be better? And how is this supposed to work? The city classification requires all the residential roads to be classified already, at least the way I was doing this so far.